import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Populer from "../components/populer";

export default function Home({ movies }) {
  console.log(movies.results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Populer filmler</h2>

    <Populer movies={movies}/>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=d3979df656135c96a122306d37e8a456&language=en-US&page=1`
  );
  const movies = await res.json();
  return {
    props: {
      movies,
    },
  };
}
